obstacle_range: 5
raytrace_range: 10.0
footprint: [[0.15, 0.20], [0.15, -0.30], [-0.15, -0.30], [-0.15, 0.20]]
#robot_radius: ir_of_robot
inflation_radius: 0.5 #1.0
cost_scaling_factor: 0.5 #10
observation_sources: laser_scan_sensor
laser_scan_sensor: {
  #sensor_frame: laser, 
  topic: /scan, #/base_scan,
  data_type: LaserScan, 
  expected_update_rate: 1.0,
  observation_persistence: 0.0, 
  marking: true, 
  clearing: true, 
  max_obstacle_height: 1.0, 
  min_obstacle_height: -0.15
  }  

transform_tolerance: 1.5